name: Base workflow
run-name: ${{github.actor}} is testing
on:
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - name: Named step
        run: echo "Named step"
      - run: echo "${{ job.status }}"
