name: Playwright
run-name: Testing on branch ${{github.base_ref}}
on:
  pull_request:
jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM packages
        run: npm ci
      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
